name: feature
on:
  push:
    branches:
      - "*/**"
      - "!deployment/development"
jobs:
  static-check:
    uses: ./.github/workflows/_static_check.yml
  terraform-dry-run:
    uses: ./.github/workflows/_terraform.yml
    with:
      stage: dev
      should_apply: false
      role-to-assume: arn:aws:iam::105785188161:role/oidc-github-actions-role
